/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BtnGroup: typeof import('./src/components/btn-group/index.vue')['default']
    CanvasToolbar: typeof import('./src/components/canvas-toolbar/index.vue')['default']
    ColorSelect: typeof import('./src/components/color-select/index.vue')['default']
    ContextMenu: typeof import('./src/components/context-menu/index.vue')['default']
    GraphicalToolbar: typeof import('./src/components/graphical-toolbar/index.vue')['default']
    Icon: typeof import('./src/components/icon/index.vue')['default']
    IconBtn: typeof import('./src/components/icon-btn/index.vue')['default']
    OperationToolbar: typeof import('./src/components/operation-toolbar/index.vue')['default']
    Slider: typeof import('./src/components/slider/index.vue')['default']
    StyleToolbar: typeof import('./src/components/style-toolbar/index.vue')['default']
    UploadFile: typeof import('./src/components/uploadFile/index.vue')['default']
    UserManual: typeof import('./src/components/user-manual/index.vue')['default']
  }
}
